[package]
name = "r2d2_postgres"
version = "0.0.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[lib]
name = "r2d2_postgres"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies.postgres]
git = "https://github.com/alexcrichton/rust-postgres"
branch = "servo-url"

[dependencies.r2d2]
git = "https://github.com/sfackler/r2d2"
